# Generated by Django 3.0.7 on 2020-09-01 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0003_auto_20200901_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 22, 37, 10, 571550)),
        ),
    ]
