# Generated by Django 3.0.7 on 2020-09-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20200901_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
